import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
// import './index.css'
import App from './App.jsx'
import '../node_modules/bootstrap/dist/css/bootstrap.css'
import '../node_modules/bootstrap-icons/font/bootstrap-icons.css'
import '../node_modules/bootstrap/dist/js/bootstrap.bundle.js'
 import {NetflixIndex} from './components/netflix/netflix-index.jsx'
import { DataBinding } from './components/data-binding/data-binding.jsx'
import { DataApi } from './components/data-binding/api.jsx'
import { DataFetch } from './components/data-binding/fetch.jsx'
import { DataAxios } from './components/data-binding/axios.jsx'
import { EventBinding } from './components/event-Binding/event-binding.jsx'
import { EventBindingSearch } from './components/event-Binding/event-binding-search.jsx'
import { EventonChange } from './components/event-Binding/onchange.jsx'
import { MouseDemo } from './components/mouse-demo/mouse-demo.jsx'
import { MouseAnimation } from './components/mouse-demo/mouse-animation.jsx'
import { KeyDemo } from './components/keyboard-element-demo/keyboard-demo.jsx'
import { EMICalculator } from './components/keyboard-element-demo/emi-calculator.jsx'
import { ButtonDemo } from './components/keyboard-element-demo/button-demo.jsx'
import { ThrottleDemo } from './components/time-demo/throttle.jsx'
import { StopWatch } from './components/time-demo/stop-watch.jsx'
import { FakeStoreDemo } from './components/api-demo/fakestore.jsx'
import { FormDemo } from './components/form-demo/form-demo.jsx'
import { FormFormik } from './components/form-demo/custom-validation.jsx'
import { FormDemoYup } from './components/form-demo/yup-validation.jsx'
import { YupForm } from './components/api-demo/yup-form.jsx'
import { FormikDemo } from './components/form-demo/formik.jsx'
import { FormNew } from './components/form-demo/form-new.jsx'
import { DataGrid } from './controlled-components/data-grid.jsx'
import { ControlledDemo } from './controlled-components/controlled-demo.jsx'
import { ConditionDemo } from './components/conditional-demo/conditional-demo.jsx'
import { ContextDemo } from './components/context-demo/context-demo.jsx'
import { FakestoreIndex } from './fakestore/fakestore-index.jsx'

createRoot(document.getElementById('root')).render(
  
    
     < FakestoreIndex />

)
